//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Binus.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentIntelligences
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AssessmentIntelligences()
        {
            this.ScoreIntelligences = new HashSet<ScoreIntelligences>();
            this.StatementIntelligences = new HashSet<StatementIntelligences>();
        }
    
        public int AssessmentIntelligenceID { get; set; }
        public int AssessmentID { get; set; }
    
        public virtual Assessments Assessment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScoreIntelligences> ScoreIntelligences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StatementIntelligences> StatementIntelligences { get; set; }
    }
}
