//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Binus.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BinusEntities : DbContext
    {
        public BinusEntities()
            : base("name=BinusEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Assessment_1> Assessment_1 { get; set; }
        public virtual DbSet<AssessmentTypes> AssessmentTypes1 { get; set; }
        public virtual DbSet<Languages> Languages1 { get; set; }
        public virtual DbSet<StatementDetails> StatementDetails1 { get; set; }
        public virtual DbSet<Statements> Statements1 { get; set; }
    }
}
