//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Binus.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BinusEntities : DbContext
    {
        public BinusEntities()
            : base("name=BinusEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agreements> Agreements1 { get; set; }
        public virtual DbSet<AssessmentIntelligences> AssessmentIntelligences1 { get; set; }
        public virtual DbSet<AssessmentProcrasinators> AssessmentProcrasinators1 { get; set; }
        public virtual DbSet<Assessments> Assessments1 { get; set; }
        public virtual DbSet<AssessmentSensories> AssessmentSensories1 { get; set; }
        public virtual DbSet<AssessmentTypes> AssessmentTypes1 { get; set; }
        public virtual DbSet<Languages> Languages1 { get; set; }
        public virtual DbSet<ScoreIntelligences> ScoreIntelligences1 { get; set; }
        public virtual DbSet<ScoreProcrasinator> ScoreProcrasinators { get; set; }
        public virtual DbSet<ScoreSensories> ScoreSensories1 { get; set; }
        public virtual DbSet<Sensories> Sensories1 { get; set; }
        public virtual DbSet<StatementDetailIntelligences> StatementDetailIntelligences1 { get; set; }
        public virtual DbSet<StatementIntelligences> StatementIntelligences1 { get; set; }
        public virtual DbSet<StatementProcrasinators> StatementProcrasinators1 { get; set; }
        public virtual DbSet<StatementSensories> StatementSensories1 { get; set; }
    }
}
