//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Binus.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BinusEntities : DbContext
    {
        public BinusEntities()
            : base("name=BinusEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<assessment_types> assessment_types { get; set; }
        public virtual DbSet<languages> languages1 { get; set; }
        public virtual DbSet<assessment_1> assessment_1 { get; set; }
        public virtual DbSet<statement_details> statement_details { get; set; }
        public virtual DbSet<statements> statements1 { get; set; }
    }
}
