//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Binus.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultAssessments
    {
        public int ResultAssessmentID { get; set; }
        public int AssessmentID { get; set; }
        public string Institution { get; set; }
        public string AcademikCareer { get; set; }
        public string Campus { get; set; }
        public string AcademicGroup { get; set; }
        public string AcademicOrganization { get; set; }
        public string AcademicProgram { get; set; }
        public string AcademicYear { get; set; }
        public string Status { get; set; }
        public string BinusianID { get; set; }
        public string Result { get; set; }
        public string Describe { get; set; }
    
        public virtual Assessments Assessment { get; set; }
    }
}
