//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Binus.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatementIntelligences
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StatementIntelligences()
        {
            this.StatementDetailIntelligences = new HashSet<StatementDetailIntelligences>();
        }
    
        public int StatementIntelligenceID { get; set; }
        public int AssessmentIntelligenceID { get; set; }
        public string StatementIntelligence { get; set; }
    
        public virtual AssessmentIntelligences AssessmentIntelligence { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StatementDetailIntelligences> StatementDetailIntelligences { get; set; }
    }
}
