//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Binus.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatementSensories
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StatementSensories()
        {
            this.Sensories = new HashSet<Sensories>();
        }
    
        public int StatementSensoryID { get; set; }
        public int AssessmentSensoryID { get; set; }
        public string StatementSensory { get; set; }
    
        public virtual AssessmentSensories AssessmentSensory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sensories> Sensories { get; set; }
    }
}
