//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Binus.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class statement_details
    {
        public int statement_detail_id { get; set; }
        public Nullable<int> statement_id { get; set; }
        public string statement_detail { get; set; }
    
        public virtual statements statement { get; set; }
    }
}
